UPDATE find SET object_no = "23427BE20-135/007/002a; BE20-135/007/002b; BE20-135/007/002c, BE20-135/007/002d" WHERE id = 23427;

UPDATE find SET category_no = "F3279-F3280,F3300-F3303,F3344-F3345,F3346-F3349,F3374,F3375,F3376-F3378" WHERE id = 27614;

UPDATE find SET weight = "10728=10143(1193+769+371+704+1020+516+394+1322+1000+1871+250+154+579, tridacna)+585(other)" WHERE id = 22039;

UPDATE find SET object = "beaker, cut decoration, body shard (fine cut grooves) colorless glass" WHERE id = 2970;
UPDATE find SET object = "bodysherd of conical lamp, colorless glass with greenish tinge, large, oval blue blob, golden layer of weathering" WHERE id = 4675;
UPDATE find SET object = "body sherd of beacker emerald geen glass, trasparent & translucent, cracket off & very well grounded, two horizontal grooves" WHERE id = 4676;
UPDATE find SET object = "neck of bottle with frag of handle of flask, coloress glass, greenish tinge, light brown weathering" WHERE id = 4679;
UPDATE find SET object = "windowpane, cylinder blound, light greenish glass, matt & glossy, lot of elongated bubbles, brown weathering" WHERE id = 4680;
UPDATE find SET object = "sidewall of pillar mouded bowl, green glass, 1 preserved rim, signs of tooling" WHERE id = 4681;
UPDATE find SET object = "body sherd of beaker with painted decoration (frag of brownish-red & yellow lines)" WHERE id = 4693;
UPDATE find SET object = "body sherd of beaker with cut decoration (2 horizontal grooves), cracked off rim, grounded" WHERE id = 4694;
UPDATE find SET object = "body sherd of gobled with cut decoration ( row off vertical ovals & large 1 oval)" WHERE id = 4711;
UPDATE find SET object = "body sherd of bowl with cut decoration (4 horizontal lines rounded rim, thick glass)" WHERE id = 4718;
UPDATE find SET object = "body sherd of bowl,  with thick ridge, thick glass, colorless glass" WHERE id = 4719;
UPDATE find SET object = "large frag of shallow bowl with cracked off rim & 2 concetric circulars on outside" WHERE id = 4720;
UPDATE find SET object = "body sherds of moulded beaker with cracked off rim(2 rowes of vertical flutes & indentetions forming honeycomb pattern, good quality cobald blue glass)" WHERE id = 4721;
UPDATE find SET object = "body sherd of gobled with cut decoration (vertical ovals & 2 horizontal lines)" WHERE id = 4726;
UPDATE find SET object = "body sherd of bottle? with abraded decoration (with floral motifs, thick glass)" WHERE id = 4730;
UPDATE find SET object = "body sherd of bowl with abraded decoration, horizontal diagonal lines" WHERE id = 4734;
UPDATE find SET object = "frag of neck of bottle with moulded decoration (vertical ovals)& applied coil" WHERE id = 4736;
UPDATE find SET object = "body sherd of moulded beaker (ovals & vertical flutes, green glass)" WHERE id = 4740;
UPDATE find SET object = "body sherd of gobled with cut decoration (3 rows of vertical ovals) colorless glass" WHERE id = 4741;
UPDATE find SET object = "body sherd of beaker with abraded decoration & frag of large facetcut oval, thick glass" WHERE id = 4750;
UPDATE find SET object = "body sherd of beaker with cut decoration (abraded lines & facet cut) thick glass" WHERE id = 4763;
UPDATE find SET object = "body sherd of conical beaker with 3 blue blobs & slighty abraded 2 horizontal lines" WHERE id = 4782;
UPDATE find SET object = "body shard of beaker with abraded decorations (lines & oval) colorless glass" WHERE id = 4785;
UPDATE find SET object = "body shard of beaker with cut decoration (2 shallow grooves) colorless glass" WHERE id = 4786;
UPDATE find SET object = "body shard of bowl with cut decoration (groove & elongated ovals) colorless glass" WHERE id = 4790;
UPDATE find SET object = "body shard of conical lamp of cracked off rim & 2 horizontal rows of indents, very thick, low quality glass" WHERE id = 4795;
UPDATE find SET object = "body shard of  shallow bowl with cracked off rim, thin glass, rim very well grounded" WHERE id = 4806;
UPDATE find SET object = "body shard of beaker with cut decoration (honeycomb pattern)colorless glass" WHERE id = 4809;
UPDATE find SET object = "base frag of shallow bowl with 2 concentic circles on bottle, on outside thin glass" WHERE id = 4811;
UPDATE find SET object = "body shard of bottle of cut decoration (ovals & rice grain faces colorless glass" WHERE id = 4816;
UPDATE find SET object = "body shard of beaker with moulded decoration (honeycomb pattern) brown glass" WHERE id = 4820;
UPDATE find SET object = "cameo glass (bottle?) colorless glass & blue overlay, cut decoration" WHERE id = 4831;
UPDATE find SET object = "frag of beaker (cut decoration, 4 horizontal grooves, thin colorless glass)" WHERE id = 4833;
UPDATE find SET object = "base of bottle with cut decoration, 4 horizontal grooves, colorless glass" WHERE id = 4834;
UPDATE find SET object = "frag of shallow bowl with cracked off rim (cut grooves) colorless glass" WHERE id = 4836;
UPDATE find SET object = "body sherd of bottle with cut decoration (ovals rice grain motif square withe cross hatching" WHERE id = 4839;
UPDATE find SET object = "body sherd of beaker with cut cecoration (flower like motif) colorless glass" WHERE id = 4840;
UPDATE find SET object = "body shard of gobled with cut decoration, 2 rows elongated ovals, colorless glass" WHERE id = 4841;
UPDATE find SET object = "body shard of gobled with cut decoration (2 horizontal rows of elongated ovals" WHERE id = 4842;
UPDATE find SET object = "body shard of hemispherical bowl with cracked off rim, with cut decoration (2 horizontal rows of amylogdoid ovals, colores glass" WHERE id = 4843;
UPDATE find SET object = "frag of beaker with cut decoration (horizontal grooves & row elongated ovals) colorless glass" WHERE id = 4844;
UPDATE find SET object = "body shard of beaker with cut decoration, large ovals & horizontal grooves" WHERE id = 4845;
UPDATE find SET object = "body shard of hemispherical bowl with cracked off rim & 1 blue blob" WHERE id = 4846;
UPDATE find SET object = "base of bowl with cut decoration, horizontal row of elongated ovals, colorless glass" WHERE id = 4848;
UPDATE find SET object = "base of  bowl (ring base) on the bottom on under side cut rosett, colorless glass" WHERE id = 4850;
UPDATE find SET object = "frag of large beaker with cut decoration (grooves & large elongated ovals)" WHERE id = 4851;
UPDATE find SET object = "body shard of bowl with cut decoration (horizontal groov & 3 rows of elongated ovals, colorless glass)" WHERE id = 4857;
UPDATE find SET object = "body shard of beaker with cut decoration (row of rise grain ovals, colorless glass" WHERE id = 4858;
UPDATE find SET object = "body shard of beaker with cut decoration (frag of wing of large birde, colorless glass)" WHERE id = 4859;
UPDATE find SET object = "body shard of pillar moulded bowl, 2 ribs preserved, signs of tooling, yellowish-greenish, bubbles" WHERE id = 4863;
UPDATE find SET object = "body shard of pillar moulded bowl, 3 ribs preserved, signs of tooling, yellow-green glass, bubbles" WHERE id = 4864;
UPDATE find SET object = "body shard of pillar moulded bowl, 4 ribs preserved, signs of tooling, green glass," WHERE id = 4865;
UPDATE find SET object = "body shard of pillar moulded bowl, 3 ribs preserved, signs of tooling, green glass,bubbles" WHERE id = 4866;
UPDATE find SET object = "base of boottle (moulded) on the bottom on outside partialy preserved letter L, very thick green glass, bubbles" WHERE id = 4867;
UPDATE find SET object = "rectangular base of moulded bottle, light -olive green glass, bubbles" WHERE id = 4868;
UPDATE find SET object = "base frag of moulded bottle(2 concentric circles), light green glass" WHERE id = 4869;
UPDATE find SET object = "neck of bottle green glass with yellowish streaks, lot of elongated bubbles, some impurities" WHERE id = 4871;
UPDATE find SET object = "windowpane flet, bluish greenish glass bubbles, 1 original edge preserved" WHERE id = 4879;
UPDATE find SET object = "frag of windowpane flet, light yellowish green glass, bubbles, cylinder blown" WHERE id = 4880;
UPDATE find SET object = "frag of windowpane flet glass, light yellowish green glass, bubbles, cylinder blown" WHERE id = 4881;
UPDATE find SET object = "pot, Axumite, flat-rimmed with horizontal twirled handle, with food remains" WHERE id = 21360;
UPDATE find SET object = "body sherd of beaker cobalt blue glass, transparent & translucent, rounded rim horizontal cut line below rim" WHERE id = 4677;