-- tm

UPDATE find SET tm = 261 WHERE id = 261;
UPDATE find SET tm = 262 WHERE id = 8799;
UPDATE find SET tm = 264 WHERE id = 287;
UPDATE find SET tm = 265 WHERE id = 265;
UPDATE find SET tm = 267 WHERE id = 272;
UPDATE find SET tm = 269 WHERE id = 262;
UPDATE find SET tm = 270 WHERE id = 6391;
UPDATE find SET tm = 271 WHERE id = 288;
UPDATE find SET tm = 272 WHERE id = 2196;
UPDATE find SET tm = 273 WHERE id = 1959;
UPDATE find SET tm = 274 WHERE id = 8;
UPDATE find SET tm = 275 WHERE id = 9;
UPDATE find SET tm = 276 WHERE id = 12;
UPDATE find SET tm = 277 WHERE id = 13;
UPDATE find SET tm = 278 WHERE id = 14;
UPDATE find SET tm = 279 WHERE id = 15;
UPDATE find SET tm = 280 WHERE id = 16;
UPDATE find SET tm = 281 WHERE id = 17;
UPDATE find SET tm = 282 WHERE id = 18;
UPDATE find SET tm = 283 WHERE id = 19;
UPDATE find SET tm = 284 WHERE id = 21;
UPDATE find SET tm = 285 WHERE id = 23;
UPDATE find SET tm = 286 WHERE id = 28;
UPDATE find SET tm = 287 WHERE id = 30;
UPDATE find SET tm = 288 WHERE id = 31;
UPDATE find SET tm = 289 WHERE id = 32;
UPDATE find SET tm = 290 WHERE id = 36;
UPDATE find SET tm = 291 WHERE id = 37;
UPDATE find SET tm = 292 WHERE id = 38;
UPDATE find SET tm = 293 WHERE id = 42;
UPDATE find SET tm = 294 WHERE id = 43;
UPDATE find SET tm = 295 WHERE id = 194;
UPDATE find SET tm = 295 WHERE id = 48;
UPDATE find SET tm = 296 WHERE id = 49;
UPDATE find SET tm = 297 WHERE id = 52;
UPDATE find SET tm = 298 WHERE id = 53;
UPDATE find SET tm = 299 WHERE id = 54;
UPDATE find SET tm = 300 WHERE id = 57;
UPDATE find SET tm = 301 WHERE id = 58;
UPDATE find SET tm = 302 WHERE id = 60;
UPDATE find SET tm = 303 WHERE id = 61;
UPDATE find SET tm = 304 WHERE id = 64;
UPDATE find SET tm = 305 WHERE id = 65;
UPDATE find SET tm = 306 WHERE id = 68;
UPDATE find SET tm = 307 WHERE id = 69;
UPDATE find SET tm = 308 WHERE id = 70;
UPDATE find SET tm = 309 WHERE id = 72;
UPDATE find SET tm = 310 WHERE id = 74;
UPDATE find SET tm = 311 WHERE id = 75;
UPDATE find SET tm = 312 WHERE id = 76;
UPDATE find SET tm = 312 WHERE id = 77;
UPDATE find SET tm = 313 WHERE id = 41;
UPDATE find SET tm = 314 WHERE id = 82;
UPDATE find SET tm = 315 WHERE id = 83;
UPDATE find SET tm = 316 WHERE id = 84;
UPDATE find SET tm = 317 WHERE id = 85;
UPDATE find SET tm = 318 WHERE id = 86;
UPDATE find SET tm = 319 WHERE id = 45;
UPDATE find SET tm = 320 WHERE id = 91;
UPDATE find SET tm = 321 WHERE id = 92;
UPDATE find SET tm = 322 WHERE id = 94;
UPDATE find SET tm = 323 WHERE id = 73;
UPDATE find SET tm = 324 WHERE id = 106;
UPDATE find SET tm = 325 WHERE id = 107;
UPDATE find SET tm = 326 WHERE id = 109;
UPDATE find SET tm = 327 WHERE id = 115;
UPDATE find SET tm = 328 WHERE id = 117;
UPDATE find SET tm = 329 WHERE id = 118;
UPDATE find SET tm = 330 WHERE id = 119;
UPDATE find SET tm = 331 WHERE id = 120;
UPDATE find SET tm = 332 WHERE id = 121;
UPDATE find SET tm = 333 WHERE id = 123;
UPDATE find SET tm = 334 WHERE id = 125;
UPDATE find SET tm = 336 WHERE id = 128;
UPDATE find SET tm = 337 WHERE id = 132;
UPDATE find SET tm = 338 WHERE id = 134;
UPDATE find SET tm = 339 WHERE id = 135;
UPDATE find SET tm = 340 WHERE id = 137;
UPDATE find SET tm = 341 WHERE id = 138;
UPDATE find SET tm = 342 WHERE id = 142;
UPDATE find SET tm = 343 WHERE id = 143;
UPDATE find SET tm = 344 WHERE id = 146;
UPDATE find SET tm = 345 WHERE id = 147;
UPDATE find SET tm = 346 WHERE id = 149;
UPDATE find SET tm = 347 WHERE id = 150;
UPDATE find SET tm = 348 WHERE id = 152;
UPDATE find SET tm = 349 WHERE id = 153;
UPDATE find SET tm = 350 WHERE id = 154;
UPDATE find SET tm = 351 WHERE id = 155;
UPDATE find SET tm = 352 WHERE id = 156;
UPDATE find SET tm = 353 WHERE id = 157;
UPDATE find SET tm = 354 WHERE id = 159;
UPDATE find SET tm = 355 WHERE id = 160;
UPDATE find SET tm = 356 WHERE id = 161;
UPDATE find SET tm = 357 WHERE id = 162;
UPDATE find SET tm = 358 WHERE id = 163;
UPDATE find SET tm = 359 WHERE id = 164;
UPDATE find SET tm = 360 WHERE id = 165;
UPDATE find SET tm = 361 WHERE id = 166;
UPDATE find SET tm = 362 WHERE id = 168;
UPDATE find SET tm = 363 WHERE id = 170;
UPDATE find SET tm = 364 WHERE id = 171;
UPDATE find SET tm = 365 WHERE id = 172;
UPDATE find SET tm = 366 WHERE id = 173;
UPDATE find SET tm = 367 WHERE id = 174;
UPDATE find SET tm = 368 WHERE id = 175;
UPDATE find SET tm = 370 WHERE id = 228;
UPDATE find SET tm = 370 WHERE id = 230;
UPDATE find SET tm = 371 WHERE id = 192;
UPDATE find SET tm = 372 WHERE id = 196;
UPDATE find SET tm = 373 WHERE id = 197;
UPDATE find SET tm = 374 WHERE id = 201;
UPDATE find SET tm = 375 WHERE id = 206;
UPDATE find SET tm = 376 WHERE id = 207;
UPDATE find SET tm = 377 WHERE id = 208;
UPDATE find SET tm = 378 WHERE id = 209;
UPDATE find SET tm = 379 WHERE id = 211;
UPDATE find SET tm = 380 WHERE id = 212;
UPDATE find SET tm = 381 WHERE id = 213;
UPDATE find SET tm = 382 WHERE id = 214;
UPDATE find SET tm = 383 WHERE id = 215;
UPDATE find SET tm = 384 WHERE id = 216;
UPDATE find SET tm = 385 WHERE id = 217;
UPDATE find SET tm = 386 WHERE id = 218;
UPDATE find SET tm = 387 WHERE id = 220;
UPDATE find SET tm = 388 WHERE id = 221;
UPDATE find SET tm = 389 WHERE id = 222;
UPDATE find SET tm = 390 WHERE id = 223;
UPDATE find SET tm = 391 WHERE id = 224;
UPDATE find SET tm = 392 WHERE id = 225;
UPDATE find SET tm = 393 WHERE id = 226;
UPDATE find SET tm = 394 WHERE id = 227;
UPDATE find SET tm = 395 WHERE id = 229;
UPDATE find SET tm = 396 WHERE id = 231;
UPDATE find SET tm = 397 WHERE id = 232;
UPDATE find SET tm = 398 WHERE id = 233;
UPDATE find SET tm = 399 WHERE id = 234;
UPDATE find SET tm = 400 WHERE id = 236;
UPDATE find SET tm = 401 WHERE id = 237;
UPDATE find SET tm = 402 WHERE id = 238;
UPDATE find SET tm = 403 WHERE id = 239;
UPDATE find SET tm = 404 WHERE id = 240;
UPDATE find SET tm = 406 WHERE id = 242;
UPDATE find SET tm = 407 WHERE id = 243;
UPDATE find SET tm = 408 WHERE id = 244;
UPDATE find SET tm = 409 WHERE id = 253;
UPDATE find SET tm = 410 WHERE id = 254;
UPDATE find SET tm = 411 WHERE id = 255;
UPDATE find SET tm = 412 WHERE id = 257;
UPDATE find SET tm = 413 WHERE id = 258;
UPDATE find SET tm = 414 WHERE id = 111;
UPDATE find SET tm = 414 WHERE id = 199;
UPDATE find SET tm = 415 WHERE id = 131;
UPDATE find SET tm = 415 WHERE id = 191;
UPDATE find SET tm = 416 WHERE id = 20;
UPDATE find SET tm = 416 WHERE id = 34;
UPDATE find SET tm = 417 WHERE id = 151;
UPDATE find SET tm = 417 WHERE id = 183;
UPDATE find SET tm = 418 WHERE id = 195;
UPDATE find SET tm = 418 WHERE id = 22;
UPDATE find SET tm = 418 WHERE id = 59;
UPDATE find SET tm = 418 WHERE id = 95;
UPDATE find SET tm = 419 WHERE id = 158;
UPDATE find SET tm = 419 WHERE id = 169;
UPDATE find SET tm = 419 WHERE id = 179;
UPDATE find SET tm = 420 WHERE id = 124;
UPDATE find SET tm = 420 WHERE id = 24;
UPDATE find SET tm = 420 WHERE id = 25;
UPDATE find SET tm = 421 WHERE id = 188;
UPDATE find SET tm = 421 WHERE id = 26;
UPDATE find SET tm = 422 WHERE id = 27;
UPDATE find SET tm = 422 WHERE id = 46;
UPDATE find SET tm = 423 WHERE id = 29;
UPDATE find SET tm = 423 WHERE id = 47;
UPDATE find SET tm = 424 WHERE id = 33;
UPDATE find SET tm = 424 WHERE id = 44;
UPDATE find SET tm = 425 WHERE id = 35;
UPDATE find SET tm = 425 WHERE id = 51;
UPDATE find SET tm = 426 WHERE id = 10;
UPDATE find SET tm = 426 WHERE id = 55;
UPDATE find SET tm = 427 WHERE id = 141;
UPDATE find SET tm = 427 WHERE id = 39;
UPDATE find SET tm = 428 WHERE id = 11;
UPDATE find SET tm = 428 WHERE id = 167;
UPDATE find SET tm = 429 WHERE id = 122;
UPDATE find SET tm = 429 WHERE id = 50;
UPDATE find SET tm = 430 WHERE id = 148;
UPDATE find SET tm = 430 WHERE id = 56;
UPDATE find SET tm = 431 WHERE id = 101;
UPDATE find SET tm = 431 WHERE id = 200;
UPDATE find SET tm = 431 WHERE id = 62;
UPDATE find SET tm = 431 WHERE id = 88;
UPDATE find SET tm = 432 WHERE id = 63;
UPDATE find SET tm = 432 WHERE id = 79;
UPDATE find SET tm = 432 WHERE id = 97;
UPDATE find SET tm = 433 WHERE id = 116;
UPDATE find SET tm = 433 WHERE id = 129;
UPDATE find SET tm = 433 WHERE id = 190;
UPDATE find SET tm = 433 WHERE id = 66;
UPDATE find SET tm = 434 WHERE id = 67;
UPDATE find SET tm = 434 WHERE id = 98;
UPDATE find SET tm = 435 WHERE id = 210;
UPDATE find SET tm = 435 WHERE id = 71;
UPDATE find SET tm = 436 WHERE id = 78;
UPDATE find SET tm = 436 WHERE id = 96;
UPDATE find SET tm = 437 WHERE id = 103;
UPDATE find SET tm = 437 WHERE id = 108;
UPDATE find SET tm = 437 WHERE id = 241;
UPDATE find SET tm = 437 WHERE id = 80;
UPDATE find SET tm = 438 WHERE id = 102;
UPDATE find SET tm = 438 WHERE id = 81;
UPDATE find SET tm = 438 WHERE id = 90;
UPDATE find SET tm = 439 WHERE id = 100;
UPDATE find SET tm = 439 WHERE id = 87;
UPDATE find SET tm = 440 WHERE id = 130;
UPDATE find SET tm = 440 WHERE id = 133;
UPDATE find SET tm = 440 WHERE id = 89;
UPDATE find SET tm = 441 WHERE id = 110;
UPDATE find SET tm = 441 WHERE id = 113;
UPDATE find SET tm = 441 WHERE id = 193;
UPDATE find SET tm = 441 WHERE id = 99;
UPDATE find SET tm = 442 WHERE id = 104;
UPDATE find SET tm = 442 WHERE id = 114;
UPDATE find SET tm = 442 WHERE id = 204;
UPDATE find SET tm = 443 WHERE id = 105;
UPDATE find SET tm = 443 WHERE id = 112;
UPDATE find SET tm = 444 WHERE id = 40;
UPDATE find SET tm = 490 WHERE id = 249;
UPDATE find SET tm = 508 WHERE id = 181;

-- publications

UPDATE find SET publicattions = "O. Berenike 3 261" WHERE id = 261;
UPDATE find SET publicattions = "O. Berenike 3 262" WHERE id = 8799;
UPDATE find SET publicattions = "O. Berenike 3 264" WHERE id = 287;
UPDATE find SET publicattions = "O. Berenike 3 265" WHERE id = 265;
UPDATE find SET publicattions = "O. Berenike 3 267" WHERE id = 272;
UPDATE find SET publicattions = "O. Berenike 3 269" WHERE id = 262;
UPDATE find SET publicattions = "O. Berenike 3 270" WHERE id = 6391;
UPDATE find SET publicattions = "O. Berenike 3 271" WHERE id = 288;
UPDATE find SET publicattions = "O. Berenike 3 272" WHERE id = 2196;
UPDATE find SET publicattions = "O. Berenike 3 273" WHERE id = 1959;
UPDATE find SET publicattions = "O. Berenike 3 274" WHERE id = 8;
UPDATE find SET publicattions = "O. Berenike 3 275" WHERE id = 9;
UPDATE find SET publicattions = "O. Berenike 3 276" WHERE id = 12;
UPDATE find SET publicattions = "O. Berenike 3 277" WHERE id = 13;
UPDATE find SET publicattions = "O. Berenike 3 278" WHERE id = 14;
UPDATE find SET publicattions = "O. Berenike 3 279" WHERE id = 15;
UPDATE find SET publicattions = "O. Berenike 3 280" WHERE id = 16;
UPDATE find SET publicattions = "O. Berenike 3 281" WHERE id = 17;
UPDATE find SET publicattions = "O. Berenike 3 282" WHERE id = 18;
UPDATE find SET publicattions = "O. Berenike 3 283" WHERE id = 19;
UPDATE find SET publicattions = "O. Berenike 3 284" WHERE id = 21;
UPDATE find SET publicattions = "O. Berenike 3 285" WHERE id = 23;
UPDATE find SET publicattions = "O. Berenike 3 286" WHERE id = 28;
UPDATE find SET publicattions = "O. Berenike 3 287" WHERE id = 30;
UPDATE find SET publicattions = "O. Berenike 3 288" WHERE id = 31;
UPDATE find SET publicattions = "O. Berenike 3 289" WHERE id = 32;
UPDATE find SET publicattions = "O. Berenike 3 290" WHERE id = 36;
UPDATE find SET publicattions = "O. Berenike 3 291" WHERE id = 37;
UPDATE find SET publicattions = "O. Berenike 3 292" WHERE id = 38;
UPDATE find SET publicattions = "O. Berenike 3 293" WHERE id = 42;
UPDATE find SET publicattions = "O. Berenike 3 294" WHERE id = 43;
UPDATE find SET publicattions = "O. Berenike 3 295" WHERE id = 194;
UPDATE find SET publicattions = "O. Berenike 3 295" WHERE id = 48;
UPDATE find SET publicattions = "O. Berenike 3 296" WHERE id = 49;
UPDATE find SET publicattions = "O. Berenike 3 297" WHERE id = 52;
UPDATE find SET publicattions = "O. Berenike 3 298" WHERE id = 53;
UPDATE find SET publicattions = "O. Berenike 3 299" WHERE id = 54;
UPDATE find SET publicattions = "O. Berenike 3 300" WHERE id = 57;
UPDATE find SET publicattions = "O. Berenike 3 301" WHERE id = 58;
UPDATE find SET publicattions = "O. Berenike 3 302" WHERE id = 60;
UPDATE find SET publicattions = "O. Berenike 3 303" WHERE id = 61;
UPDATE find SET publicattions = "O. Berenike 3 304" WHERE id = 64;
UPDATE find SET publicattions = "O. Berenike 3 305" WHERE id = 65;
UPDATE find SET publicattions = "O. Berenike 3 306" WHERE id = 68;
UPDATE find SET publicattions = "O. Berenike 3 307" WHERE id = 69;
UPDATE find SET publicattions = "O. Berenike 3 308" WHERE id = 70;
UPDATE find SET publicattions = "O. Berenike 3 309" WHERE id = 72;
UPDATE find SET publicattions = "O. Berenike 3 310" WHERE id = 74;
UPDATE find SET publicattions = "O. Berenike 3 311" WHERE id = 75;
UPDATE find SET publicattions = "O. Berenike 3 312" WHERE id = 76;
UPDATE find SET publicattions = "O. Berenike 3 312" WHERE id = 77;
UPDATE find SET publicattions = "O. Berenike 3 313" WHERE id = 41;
UPDATE find SET publicattions = "O. Berenike 3 314" WHERE id = 82;
UPDATE find SET publicattions = "O. Berenike 3 315" WHERE id = 83;
UPDATE find SET publicattions = "O. Berenike 3 316" WHERE id = 84;
UPDATE find SET publicattions = "O. Berenike 3 317" WHERE id = 85;
UPDATE find SET publicattions = "O. Berenike 3 318" WHERE id = 86;
UPDATE find SET publicattions = "O. Berenike 3 319" WHERE id = 45;
UPDATE find SET publicattions = "O. Berenike 3 320" WHERE id = 91;
UPDATE find SET publicattions = "O. Berenike 3 321" WHERE id = 92;
UPDATE find SET publicattions = "O. Berenike 3 322" WHERE id = 94;
UPDATE find SET publicattions = "O. Berenike 3 323" WHERE id = 73;
UPDATE find SET publicattions = "O. Berenike 3 324" WHERE id = 106;
UPDATE find SET publicattions = "O. Berenike 3 325" WHERE id = 107;
UPDATE find SET publicattions = "O. Berenike 3 326" WHERE id = 109;
UPDATE find SET publicattions = "O. Berenike 3 327" WHERE id = 115;
UPDATE find SET publicattions = "O. Berenike 3 328" WHERE id = 117;
UPDATE find SET publicattions = "O. Berenike 3 329" WHERE id = 118;
UPDATE find SET publicattions = "O. Berenike 3 330" WHERE id = 119;
UPDATE find SET publicattions = "O. Berenike 3 331" WHERE id = 120;
UPDATE find SET publicattions = "O. Berenike 3 332" WHERE id = 121;
UPDATE find SET publicattions = "O. Berenike 3 333" WHERE id = 123;
UPDATE find SET publicattions = "O. Berenike 3 334" WHERE id = 125;
UPDATE find SET publicattions = "O. Berenike 3 335" WHERE id = 127;
UPDATE find SET publicattions = "O. Berenike 3 336" WHERE id = 128;
UPDATE find SET publicattions = "O. Berenike 3 337" WHERE id = 132;
UPDATE find SET publicattions = "O. Berenike 3 338" WHERE id = 134;
UPDATE find SET publicattions = "O. Berenike 3 339" WHERE id = 135;
UPDATE find SET publicattions = "O. Berenike 3 340" WHERE id = 137;
UPDATE find SET publicattions = "O. Berenike 3 341" WHERE id = 138;
UPDATE find SET publicattions = "O. Berenike 3 342" WHERE id = 142;
UPDATE find SET publicattions = "O. Berenike 3 343" WHERE id = 143;
UPDATE find SET publicattions = "O. Berenike 3 344" WHERE id = 146;
UPDATE find SET publicattions = "O. Berenike 3 345" WHERE id = 147;
UPDATE find SET publicattions = "O. Berenike 3 346" WHERE id = 149;
UPDATE find SET publicattions = "O. Berenike 3 347" WHERE id = 150;
UPDATE find SET publicattions = "O. Berenike 3 348" WHERE id = 152;
UPDATE find SET publicattions = "O. Berenike 3 349" WHERE id = 153;
UPDATE find SET publicattions = "O. Berenike 3 350" WHERE id = 154;
UPDATE find SET publicattions = "O. Berenike 3 351" WHERE id = 155;
UPDATE find SET publicattions = "O. Berenike 3 352" WHERE id = 156;
UPDATE find SET publicattions = "O. Berenike 3 353" WHERE id = 157;
UPDATE find SET publicattions = "O. Berenike 3 354" WHERE id = 159;
UPDATE find SET publicattions = "O. Berenike 3 355" WHERE id = 160;
UPDATE find SET publicattions = "O. Berenike 3 356" WHERE id = 161;
UPDATE find SET publicattions = "O. Berenike 3 357" WHERE id = 162;
UPDATE find SET publicattions = "O. Berenike 3 358" WHERE id = 163;
UPDATE find SET publicattions = "O. Berenike 3 359" WHERE id = 164;
UPDATE find SET publicattions = "O. Berenike 3 360" WHERE id = 165;
UPDATE find SET publicattions = "O. Berenike 3 361" WHERE id = 166;
UPDATE find SET publicattions = "O. Berenike 3 362" WHERE id = 168;
UPDATE find SET publicattions = "O. Berenike 3 363" WHERE id = 170;
UPDATE find SET publicattions = "O. Berenike 3 364" WHERE id = 171;
UPDATE find SET publicattions = "O. Berenike 3 365" WHERE id = 172;
UPDATE find SET publicattions = "O. Berenike 3 366" WHERE id = 173;
UPDATE find SET publicattions = "O. Berenike 3 367" WHERE id = 174;
UPDATE find SET publicattions = "O. Berenike 3 368" WHERE id = 175;
UPDATE find SET publicattions = "O. Berenike 3 369 & 419" WHERE id = 177;
UPDATE find SET publicattions = "O. Berenike 3 370" WHERE id = 228;
UPDATE find SET publicattions = "O. Berenike 3 370" WHERE id = 230;
UPDATE find SET publicattions = "O. Berenike 3 371" WHERE id = 192;
UPDATE find SET publicattions = "O. Berenike 3 372" WHERE id = 196;
UPDATE find SET publicattions = "O. Berenike 3 373" WHERE id = 197;
UPDATE find SET publicattions = "O. Berenike 3 374" WHERE id = 201;
UPDATE find SET publicattions = "O. Berenike 3 375" WHERE id = 206;
UPDATE find SET publicattions = "O. Berenike 3 376" WHERE id = 207;
UPDATE find SET publicattions = "O. Berenike 3 377" WHERE id = 208;
UPDATE find SET publicattions = "O. Berenike 3 378" WHERE id = 209;
UPDATE find SET publicattions = "O. Berenike 3 379" WHERE id = 211;
UPDATE find SET publicattions = "O. Berenike 3 380" WHERE id = 212;
UPDATE find SET publicattions = "O. Berenike 3 381" WHERE id = 213;
UPDATE find SET publicattions = "O. Berenike 3 382" WHERE id = 214;
UPDATE find SET publicattions = "O. Berenike 3 383" WHERE id = 215;
UPDATE find SET publicattions = "O. Berenike 3 384" WHERE id = 216;
UPDATE find SET publicattions = "O. Berenike 3 385" WHERE id = 217;
UPDATE find SET publicattions = "O. Berenike 3 386" WHERE id = 218;
UPDATE find SET publicattions = "O. Berenike 3 387" WHERE id = 220;
UPDATE find SET publicattions = "O. Berenike 3 388" WHERE id = 221;
UPDATE find SET publicattions = "O. Berenike 3 389" WHERE id = 222;
UPDATE find SET publicattions = "O. Berenike 3 390" WHERE id = 223;
UPDATE find SET publicattions = "O. Berenike 3 391" WHERE id = 224;
UPDATE find SET publicattions = "O. Berenike 3 392" WHERE id = 225;
UPDATE find SET publicattions = "O. Berenike 3 393" WHERE id = 226;
UPDATE find SET publicattions = "O. Berenike 3 394" WHERE id = 227;
UPDATE find SET publicattions = "O. Berenike 3 395" WHERE id = 229;
UPDATE find SET publicattions = "O. Berenike 3 396" WHERE id = 231;
UPDATE find SET publicattions = "O. Berenike 3 397" WHERE id = 232;
UPDATE find SET publicattions = "O. Berenike 3 398" WHERE id = 233;
UPDATE find SET publicattions = "O. Berenike 3 399" WHERE id = 234;
UPDATE find SET publicattions = "O. Berenike 3 400" WHERE id = 236;
UPDATE find SET publicattions = "O. Berenike 3 401" WHERE id = 237;
UPDATE find SET publicattions = "O. Berenike 3 402" WHERE id = 238;
UPDATE find SET publicattions = "O. Berenike 3 403" WHERE id = 239;
UPDATE find SET publicattions = "O. Berenike 3 404" WHERE id = 240;
UPDATE find SET publicattions = "O. Berenike 3 406" WHERE id = 242;
UPDATE find SET publicattions = "O. Berenike 3 407" WHERE id = 243;
UPDATE find SET publicattions = "O. Berenike 3 408" WHERE id = 244;
UPDATE find SET publicattions = "O. Berenike 3 409" WHERE id = 253;
UPDATE find SET publicattions = "O. Berenike 3 410" WHERE id = 254;
UPDATE find SET publicattions = "O. Berenike 3 411" WHERE id = 255;
UPDATE find SET publicattions = "O. Berenike 3 412" WHERE id = 257;
UPDATE find SET publicattions = "O. Berenike 3 413" WHERE id = 258;
UPDATE find SET publicattions = "O. Berenike 3 414" WHERE id = 111;
UPDATE find SET publicattions = "O. Berenike 3 414" WHERE id = 199;
UPDATE find SET publicattions = "O. Berenike 3 415" WHERE id = 131;
UPDATE find SET publicattions = "O. Berenike 3 415" WHERE id = 191;
UPDATE find SET publicattions = "O. Berenike 3 416" WHERE id = 20;
UPDATE find SET publicattions = "O. Berenike 3 416" WHERE id = 34;
UPDATE find SET publicattions = "O. Berenike 3 417" WHERE id = 151;
UPDATE find SET publicattions = "O. Berenike 3 417" WHERE id = 183;
UPDATE find SET publicattions = "O. Berenike 3 418" WHERE id = 195;
UPDATE find SET publicattions = "O. Berenike 3 418" WHERE id = 22;
UPDATE find SET publicattions = "O. Berenike 3 418" WHERE id = 59;
UPDATE find SET publicattions = "O. Berenike 3 418" WHERE id = 95;
UPDATE find SET publicattions = "O. Berenike 3 419" WHERE id = 158;
UPDATE find SET publicattions = "O. Berenike 3 419" WHERE id = 169;
UPDATE find SET publicattions = "O. Berenike 3 419" WHERE id = 179;
UPDATE find SET publicattions = "O. Berenike 3 420" WHERE id = 124;
UPDATE find SET publicattions = "O. Berenike 3 420" WHERE id = 24;
UPDATE find SET publicattions = "O. Berenike 3 420" WHERE id = 25;
UPDATE find SET publicattions = "O. Berenike 3 421" WHERE id = 188;
UPDATE find SET publicattions = "O. Berenike 3 421" WHERE id = 26;
UPDATE find SET publicattions = "O. Berenike 3 422" WHERE id = 27;
UPDATE find SET publicattions = "O. Berenike 3 422" WHERE id = 46;
UPDATE find SET publicattions = "O. Berenike 3 423" WHERE id = 29;
UPDATE find SET publicattions = "O. Berenike 3 423" WHERE id = 47;
UPDATE find SET publicattions = "O. Berenike 3 424" WHERE id = 33;
UPDATE find SET publicattions = "O. Berenike 3 424" WHERE id = 44;
UPDATE find SET publicattions = "O. Berenike 3 425" WHERE id = 35;
UPDATE find SET publicattions = "O. Berenike 3 425" WHERE id = 51;
UPDATE find SET publicattions = "O. Berenike 3 426" WHERE id = 10;
UPDATE find SET publicattions = "O. Berenike 3 426" WHERE id = 55;
UPDATE find SET publicattions = "O. Berenike 3 427" WHERE id = 141;
UPDATE find SET publicattions = "O. Berenike 3 427" WHERE id = 39;
UPDATE find SET publicattions = "O. Berenike 3 428" WHERE id = 11;
UPDATE find SET publicattions = "O. Berenike 3 428" WHERE id = 167;
UPDATE find SET publicattions = "O. Berenike 3 429" WHERE id = 122;
UPDATE find SET publicattions = "O. Berenike 3 429" WHERE id = 50;
UPDATE find SET publicattions = "O. Berenike 3 430" WHERE id = 148;
UPDATE find SET publicattions = "O. Berenike 3 430" WHERE id = 56;
UPDATE find SET publicattions = "O. Berenike 3 431" WHERE id = 101;
UPDATE find SET publicattions = "O. Berenike 3 431" WHERE id = 200;
UPDATE find SET publicattions = "O. Berenike 3 431" WHERE id = 62;
UPDATE find SET publicattions = "O. Berenike 3 431" WHERE id = 88;
UPDATE find SET publicattions = "O. Berenike 3 432" WHERE id = 63;
UPDATE find SET publicattions = "O. Berenike 3 432" WHERE id = 79;
UPDATE find SET publicattions = "O. Berenike 3 432" WHERE id = 97;
UPDATE find SET publicattions = "O. Berenike 3 433" WHERE id = 116;
UPDATE find SET publicattions = "O. Berenike 3 433" WHERE id = 129;
UPDATE find SET publicattions = "O. Berenike 3 433" WHERE id = 190;
UPDATE find SET publicattions = "O. Berenike 3 433" WHERE id = 66;
UPDATE find SET publicattions = "O. Berenike 3 434" WHERE id = 67;
UPDATE find SET publicattions = "O. Berenike 3 434" WHERE id = 98;
UPDATE find SET publicattions = "O. Berenike 3 435" WHERE id = 210;
UPDATE find SET publicattions = "O. Berenike 3 435" WHERE id = 71;
UPDATE find SET publicattions = "O. Berenike 3 436" WHERE id = 78;
UPDATE find SET publicattions = "O. Berenike 3 436" WHERE id = 96;
UPDATE find SET publicattions = "O. Berenike 3 437" WHERE id = 103;
UPDATE find SET publicattions = "O. Berenike 3 437" WHERE id = 108;
UPDATE find SET publicattions = "O. Berenike 3 437" WHERE id = 241;
UPDATE find SET publicattions = "O. Berenike 3 437" WHERE id = 80;
UPDATE find SET publicattions = "O. Berenike 3 438" WHERE id = 102;
UPDATE find SET publicattions = "O. Berenike 3 438" WHERE id = 81;
UPDATE find SET publicattions = "O. Berenike 3 438" WHERE id = 90;
UPDATE find SET publicattions = "O. Berenike 3 439" WHERE id = 100;
UPDATE find SET publicattions = "O. Berenike 3 439" WHERE id = 87;
UPDATE find SET publicattions = "O. Berenike 3 440" WHERE id = 130;
UPDATE find SET publicattions = "O. Berenike 3 440" WHERE id = 133;
UPDATE find SET publicattions = "O. Berenike 3 440" WHERE id = 89;
UPDATE find SET publicattions = "O. Berenike 3 441" WHERE id = 110;
UPDATE find SET publicattions = "O. Berenike 3 441" WHERE id = 113;
UPDATE find SET publicattions = "O. Berenike 3 441" WHERE id = 193;
UPDATE find SET publicattions = "O. Berenike 3 441" WHERE id = 99;
UPDATE find SET publicattions = "O. Berenike 3 442" WHERE id = 104;
UPDATE find SET publicattions = "O. Berenike 3 442" WHERE id = 114;
UPDATE find SET publicattions = "O. Berenike 3 442" WHERE id = 204;
UPDATE find SET publicattions = "O. Berenike 3 443" WHERE id = 105;
UPDATE find SET publicattions = "O. Berenike 3 443" WHERE id = 112;
UPDATE find SET publicattions = "O. Berenike 3 444" WHERE id = 40;
UPDATE find SET publicattions = "O. Berenike 3 490" WHERE id = 249;
UPDATE find SET publicattions = "O. Berenike 3 508" WHERE id = 181;


-- inventory_number

UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 55001" WHERE id = 181;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 55004" WHERE id = 249;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57001" WHERE id = 8;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57002" WHERE id = 9;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57003" WHERE id = 12;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57004" WHERE id = 13;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57005" WHERE id = 14;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57006" WHERE id = 15;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57007" WHERE id = 16;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57008" WHERE id = 17;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57009" WHERE id = 18;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57010" WHERE id = 19;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57011" WHERE id = 21;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57012" WHERE id = 23;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57013" WHERE id = 28;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57014" WHERE id = 30;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57015" WHERE id = 31;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57016" WHERE id = 32;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57017" WHERE id = 36;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57018" WHERE id = 37;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57019" WHERE id = 38;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57020" WHERE id = 42;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57021" WHERE id = 43;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57022 + Bender el-Kebir, Archaeological storeroom 57111" WHERE id = 194;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57022 + Bender el-Kebir, Archaeological storeroom 57111" WHERE id = 48;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57023" WHERE id = 49;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57024" WHERE id = 52;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57025" WHERE id = 53;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57026" WHERE id = 54;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57027" WHERE id = 57;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57028" WHERE id = 58;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57029" WHERE id = 60;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57030" WHERE id = 61;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57031" WHERE id = 64;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57032" WHERE id = 65;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57033" WHERE id = 68;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57034" WHERE id = 69;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57035" WHERE id = 70;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57036" WHERE id = 72;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57037" WHERE id = 74;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57038" WHERE id = 75;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57039" WHERE id = 76;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57039" WHERE id = 77;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57040" WHERE id = 41;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57041" WHERE id = 82;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57042" WHERE id = 83;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57043" WHERE id = 84;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57044" WHERE id = 85;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57045" WHERE id = 86;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57046" WHERE id = 45;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57047" WHERE id = 91;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57048" WHERE id = 92;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57050" WHERE id = 94;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57051" WHERE id = 73;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57053" WHERE id = 106;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57054" WHERE id = 107;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57055" WHERE id = 109;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57056" WHERE id = 115;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57057" WHERE id = 117;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57058" WHERE id = 118;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57059" WHERE id = 119;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57060" WHERE id = 120;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57061" WHERE id = 121;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57062" WHERE id = 123;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57063 + Bender el-Kebir, Archaeological storeroom 57065" WHERE id = 125;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57066" WHERE id = 128;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57067" WHERE id = 132;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57068" WHERE id = 134;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57069" WHERE id = 135;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57071" WHERE id = 137;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57072" WHERE id = 138;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57075" WHERE id = 142;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57076" WHERE id = 143;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57079" WHERE id = 146;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57080" WHERE id = 147;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57081" WHERE id = 149;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57082" WHERE id = 150;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57083" WHERE id = 152;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57084" WHERE id = 153;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57085" WHERE id = 154;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57086" WHERE id = 155;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57087" WHERE id = 156;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57088" WHERE id = 157;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57089" WHERE id = 159;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57090" WHERE id = 160;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57091" WHERE id = 161;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57092" WHERE id = 162;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57093" WHERE id = 163;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57094" WHERE id = 164;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57095" WHERE id = 165;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57096" WHERE id = 166;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57097" WHERE id = 168;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57098" WHERE id = 170;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57099" WHERE id = 171;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57100" WHERE id = 172;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57101" WHERE id = 173;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57102" WHERE id = 174;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57103" WHERE id = 175;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57109" WHERE id = 228;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57109" WHERE id = 230;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57110" WHERE id = 192;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57112" WHERE id = 196;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57113" WHERE id = 197;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57115" WHERE id = 201;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57119" WHERE id = 206;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57120" WHERE id = 207;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57121" WHERE id = 208;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57122" WHERE id = 209;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57123" WHERE id = 211;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57124" WHERE id = 212;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57125" WHERE id = 213;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57126" WHERE id = 214;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57127" WHERE id = 215;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57128" WHERE id = 216;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57129" WHERE id = 217;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57130" WHERE id = 218;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57132" WHERE id = 220;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57133" WHERE id = 221;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57134" WHERE id = 222;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57135" WHERE id = 223;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57136" WHERE id = 224;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57137" WHERE id = 225;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57138" WHERE id = 226;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57139" WHERE id = 227;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57140" WHERE id = 229;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57141" WHERE id = 231;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57142" WHERE id = 232;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57143" WHERE id = 233;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57144" WHERE id = 234;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57146" WHERE id = 236;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57147" WHERE id = 237;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57148" WHERE id = 238;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57149" WHERE id = 239;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57150" WHERE id = 240;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57152" WHERE id = 242;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57153" WHERE id = 243;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57154" WHERE id = 244;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57159" WHERE id = 253;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57160" WHERE id = 254;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57161" WHERE id = 255;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57163" WHERE id = 257;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57164" WHERE id = 258;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57169" WHERE id = 111;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57169" WHERE id = 199;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57170" WHERE id = 131;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57170" WHERE id = 191;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57171" WHERE id = 20;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57171" WHERE id = 34;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57172" WHERE id = 151;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57172" WHERE id = 183;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57173" WHERE id = 195;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57173" WHERE id = 22;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57173" WHERE id = 59;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57173" WHERE id = 95;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57174" WHERE id = 158;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57174" WHERE id = 169;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57174" WHERE id = 179;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57175" WHERE id = 124;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57175" WHERE id = 24;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57175" WHERE id = 25;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57176" WHERE id = 188;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57176" WHERE id = 26;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57177" WHERE id = 27;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57177" WHERE id = 46;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57178" WHERE id = 29;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57178" WHERE id = 47;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57179" WHERE id = 33;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57179" WHERE id = 44;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57180" WHERE id = 35;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57180" WHERE id = 51;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57181" WHERE id = 10;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57181" WHERE id = 55;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57182" WHERE id = 141;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57182" WHERE id = 39;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57183" WHERE id = 11;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57183" WHERE id = 167;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57184" WHERE id = 122;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57184" WHERE id = 50;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57185" WHERE id = 148;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57185" WHERE id = 56;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57186" WHERE id = 101;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57186" WHERE id = 200;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57186" WHERE id = 62;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57186" WHERE id = 88;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57187" WHERE id = 63;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57187" WHERE id = 79;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57187" WHERE id = 97;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57188" WHERE id = 116;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57188" WHERE id = 129;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57188" WHERE id = 190;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57188" WHERE id = 66;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57189" WHERE id = 67;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57189" WHERE id = 98;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57190" WHERE id = 210;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57190" WHERE id = 71;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57191" WHERE id = 78;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57191" WHERE id = 96;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57192" WHERE id = 103;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57192" WHERE id = 108;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57192" WHERE id = 241;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57192" WHERE id = 80;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57193" WHERE id = 102;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57193" WHERE id = 81;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57193" WHERE id = 90;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57194" WHERE id = 100;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57194" WHERE id = 87;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57195" WHERE id = 130;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57195" WHERE id = 133;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57195" WHERE id = 89;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57196" WHERE id = 110;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57196" WHERE id = 113;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57196" WHERE id = 193;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57196" WHERE id = 99;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57197" WHERE id = 104;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57197" WHERE id = 114;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57197" WHERE id = 204;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57198" WHERE id = 105;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57198" WHERE id = 112;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57199" WHERE id = 40;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57200" WHERE id = 261;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57201" WHERE id = 288;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57202" WHERE id = 262;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57203" WHERE id = 287;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57207" WHERE id = 265;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 57214" WHERE id = 272;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 59002" WHERE id = 2196;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 60001" WHERE id = 1959;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 76008" WHERE id = 6391;
UPDATE find SET inventory_number = "Bender el-Kebir, Archaeological storeroom 84029" WHERE id = 8799;
