PapyrillioBerenike_Home:
    path:  /
    controller: App\Controller\HomeController::index

PapyrillioBerenike_Dashboard:
    path:  /dashboard
    controller: App\Controller\HomeController::dashboard

PapyrillioBerenike_Info:
    path:  /info
    controller: App\Controller\HomeController::info

PapyrillioBerenike_FindList:
    path:  /finds
    controller: App\Controller\FindController::list

PapyrillioBerenike_FindShow:
    path:  /find/{id}
    controller: App\Controller\FindController::show

PapyrillioBerenike_FindShowForHeidIcon:
    path:  /forHeidIcon/{id}
    controller: App\Controller\FindController::show

PapyrillioBerenike_FindEdit:
    path:  /find/{id}/edit
    controller: App\Controller\FindController::edit
    methods: [GET, POST]

PapyrillioBerenike_BucketList:
    path:  /buckets
    controller: App\Controller\BucketController::list

PapyrillioBerenike_BucketShow:
    path:  /bucket/{id}
    controller: App\Controller\BucketController::show

PapyrillioBerenike_BucketEdit:
    path:  /bucket/{id}/edit
    controller: App\Controller\BucketController::edit
    methods: [GET, POST]

PapyrillioBerenike_LocusList:
    path:  /loci
    controller: App\Controller\LocusController::list

PapyrillioBerenike_LocusShow:
    path:  /locus/{id}
    controller: App\Controller\LocusController::show

PapyrillioBerenike_LocusEdit:
    path:  /locus/{id}/edit
    controller: App\Controller\LocusController::edit
    methods: [GET, POST]

PapyrillioBerenike_ExcavationList:
    path:  /trenches
    controller: App\Controller\ExcavationController::list

PapyrillioBerenike_ExcavationShow:
    path:  /trench/{id}
    controller: App\Controller\ExcavationController::show

PapyrillioBerenike_ExcavationEdit:
    path:  /trench/{id}/edit
    controller: App\Controller\ExcavationController::edit
    methods: [GET, POST]

PapyrillioBerenike_AdminNewFind:
    path:  /admin/new/find
    controller: App\Controller\AdminController::newFind
    methods: [GET, POST]

PapyrillioBerenike_AdminNewBucket:
    path:  /admin/new/bucket
    controller: App\Controller\AdminController::newBucket
    methods: [GET, POST]

PapyrillioBerenike_AdminNewLocus:
    path:  /admin/new/locus
    controller: App\Controller\AdminController::newLocus
    methods: [GET, POST]

PapyrillioBerenike_AdminNewTrench:
    path:  /admin/new/trench
    controller: App\Controller\AdminController::newTrench
    methods: [GET, POST]

PapyrillioBerenike_AdminDeleteFind:
    path:  /admin/delete/find/{id}
    controller: App\Controller\AdminController::deleteFind
    methods: [POST]

PapyrillioBerenike_AdminDeleteBucket:
    path:  /admin/delete/bucket/{id}
    controller: App\Controller\AdminController::deleteBucket
    methods: [POST]

PapyrillioBerenike_AdminDeleteLocus:
    path:  /admin/delete/locus/{id}
    controller: App\Controller\AdminController::deleteLocus
    methods: [POST]

PapyrillioBerenike_AdminDeleteTrench:
    path:  /admin/delete/trench/{id}
    controller: App\Controller\AdminController::deleteTrench
    methods: [POST]

PapyrillioBerenike_Logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

PapyrillioBerenike_Login:
    path: /login
    controller: App\Controller\SecurityController::login

PapyrillioBerenike_UserChangePassword:
    path: /user/changePassword
    controller: App\Controller\UserController::changePassword

PapyrillioBerenike_UserEditProfile:
    path: /user/editProfile
    controller: App\Controller\UserController::editProfile

PapyrillioBerenike_UserList:
    path: /user/list
    controller: App\Controller\UserController::list

PapyrillioBerenike_UserNew:
    path: /user/new
    controller: App\Controller\UserController::new

PapyrillioBerenike_UserShow:
    path: /user/show/{id}
    controller: App\Controller\UserController::show
    requirements:
      id: '\d+'

PapyrillioBerenike_UserPassword:
    path: /user/password