PapyrillioBerenike_Home:
    path:  /
    controller: App\Controller\HomeController::index

PapyrillioBerenike_Dashboard:
    path:  /dashboard
    controller: App\Controller\HomeController::dashboard

PapyrillioBerenike_FindList:
    path:  /finds
    controller: App\Controller\FindController::list

PapyrillioBerenike_FindShow:
    path:  /find/{id}
    controller: App\Controller\FindController::show

PapyrillioBerenike_FindEdit:
    path:  /find/{id}/edit
    controller: App\Controller\FindController::edit
    methods: [GET, POST]

PapyrillioBerenike_BucketList:
    path:  /buckets
    controller: App\Controller\BucketController::list

PapyrillioBerenike_BucketShow:
    path:  /bucket/{id}
    controller: App\Controller\BucketController::show

PapyrillioBerenike_BucketEdit:
    path:  /bucket/{id}/edit
    controller: App\Controller\BucketController::edit
    methods: [GET, POST]

PapyrillioBerenike_LocusList:
    path:  /loci
    controller: App\Controller\LocusController::list

PapyrillioBerenike_LocusShow:
    path:  /locus/{id}
    controller: App\Controller\LocusController::show

PapyrillioBerenike_LocusEdit:
    path:  /locus/{id}/edit
    controller: App\Controller\LocusController::edit
    methods: [GET, POST]

PapyrillioBerenike_ExcavationList:
    path:  /trenches
    controller: App\Controller\ExcavationController::list

PapyrillioBerenike_ExcavationShow:
    path:  /trench/{id}
    controller: App\Controller\ExcavationController::show

PapyrillioBerenike_ExcavationEdit:
    path:  /trench/{id}/edit
    controller: App\Controller\ExcavationController::edit

